version: '3.9'

services:
  timeless_historian_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/timeless:ro
      - ./data:/timeless/data:rw
      - ./config:/timeless/config:rw